export const VOICE_NLP_INTENTS = [
  'PLAY_CARD',
  'CAST_SPELL',
  'ACTIVATE_ABILITY',
  'TAP_CARD',
  'UNTAP_CARD',
  'MOVE_CARD',
  'SHUFFLE',
  'ADVANCE_STEP',
  'SYNC_ZONE_COUNT',
  'DRAW',
  'DISCARD_CARD',
  'GAIN_LIFE',
  'LOSE_LIFE',
  'SET_LIFE',
  'DECLARE_ATTACKERS',
  'DECLARE_BLOCKERS',
  'NO_BLOCKS',
  'DECLARE_DAMAGE',
  'NEXT_TURN',
  'UNDO',
  'MULTI_ACTION',
  'NOT_ACTION',
] as const

export type VoiceNlpIntent = (typeof VOICE_NLP_INTENTS)[number]

const actionIntents = new Set<VoiceNlpIntent>(
  VOICE_NLP_INTENTS.filter((intent) => intent !== 'NOT_ACTION'),
)

export const isVoiceNlpActionIntent = (intent: string): boolean =>
  actionIntents.has(intent as VoiceNlpIntent)

/**
 * Small initial Spanish corpus for the shadow intent-classifier experiment.
 * Card names are examples only: NLP learns the action wording, while the
 * existing parser/resolver remains responsible for card identity and legality.
 *
 * Keep NOT_ACTION intentionally rich in phrases that contain Magic verbs. The
 * classifier's most important job is avoiding false positives in conversation.
 */
export const VOICE_INTENT_TRAINING_EXAMPLES: Readonly<
  Record<VoiceNlpIntent, readonly string[]>
> = {
  PLAY_CARD: [
    'bajo una isla',
    'bajo isla',
    'juego una isla',
    'pongo una isla',
    'voy a bajar una isla',
    'pues ahora bajo isla',
    'vale pues bajo una isla',
    'bueno ahora juego isla',
    'mmm pues ahora voy a bajar una isla',
    'venga bajo bosque',
    'pues nada juego sol ring',
    'ahora pongo remora',
  ],
  CAST_SPELL: [
    'lanzo counterspell',
    'casteo counterspell',
    'tiro counterspell',
    'te lanzo counterspell',
    'voy a lanzar counterspell',
    'pues lanzo remora',
    'vale ahora casteo remora',
    'bueno te tiro counterspell',
    'ahora voy a lanzar lightning bolt',
    'venga lanzo brainstorm',
  ],
  ACTIVATE_ABILITY: [
    'activo sol ring',
    'activo la habilidad de namor',
    'activo namor',
    'uso la habilidad de namor',
    'voy a activar sol ring',
    'pues activo esta habilidad',
    'vale activo la habilidad',
    'ahora uso la habilidad de esta carta',
    'canalizo eiganjo',
    'hago channel de eiganjo',
    'equipo blackblade reforged',
    'hago waterbend de katara',
  ],
  TAP_CARD: [
    'giro sol ring',
    'giro una isla',
    'giro dos islas',
    'giro namor',
    'voy a girar sol ring',
    'pues giro la isla',
    'vale ahora giro dos tierras',
    'bueno giro sol ring',
  ],
  UNTAP_CARD: [
    'enderezo sol ring',
    'enderezo la isla',
    'enderezo dos islas',
    'voy a enderezar namor',
    'pues enderezo sol ring',
    'vale enderezo mis tierras',
  ],
  MOVE_CARD: [
    'mando namor al cementerio',
    'namor va al cementerio',
    'exilio namor',
    'devuelvo sol ring a la mano',
    'muevo remora al exilio',
    'mando el comandante a la zona de mando',
    'pues namor va al cementerio',
    'vale exilio remora',
  ],
  SHUFFLE: [
    'barajo',
    'barajo mi biblioteca',
    'barajo el mazo',
    'mi oponente baraja',
    'el rival baraja',
    'pues barajo mi mazo',
  ],
  ADVANCE_STEP: [
    'voy a mantenimiento',
    'primera principal',
    'voy a combate',
    'vamos a combate',
    'segunda principal',
    'voy al final',
    'end step',
  ],
  SYNC_ZONE_COUNT: [
    'tengo siete cartas en mano',
    'me quedan cinco en mano',
    'mano siete',
    'me quedan ochenta cartas en biblioteca',
    'biblioteca ochenta',
    'mazo ochenta',
  ],
  DRAW: [
    'robo',
    'robo una',
    'robo una carta',
    'robo dos',
    'voy a robar',
    'pues robo',
    'vale ahora robo una',
    'bueno robo dos cartas',
    'venga robo',
  ],
  DISCARD_CARD: [
    'descarto una',
    'descarto una carta',
    'descarto counterspell',
    'descarto dos',
    'voy a descartar una',
    'pues descarto remora',
    'vale descarto dos cartas',
  ],
  GAIN_LIFE: [
    'gano una vida',
    'gano cinco vidas',
    'me curo tres',
    'subo tres vidas',
    'pues gano dos',
    'vale gano cinco vidas',
    'ahora me pongo tres vidas mas',
  ],
  LOSE_LIFE: [
    'pierdo una vida',
    'pierdo cinco vidas',
    'me entran cinco',
    'me llevo tres',
    'me quitan cuatro vidas',
    'pues pierdo dos',
    'vale me entran seis',
    'ahora pierdo una vida',
  ],
  SET_LIFE: [
    'me pongo en treinta vidas',
    'me quedo en veinte',
    'estoy a dieciocho vidas',
    'me pongo en treinta',
    'pues me quedo en doce',
    'vale estoy a quince',
  ],
  DECLARE_ATTACKERS: [
    'el rival ataca con elfo',
    'mi oponente ataca con dragon',
    'ataco con namor',
    'te pego con namor',
    'voy con namor',
    'ataco con todos',
    'voy con todo',
    'te pego con namor y wolverine',
    'pues ataco con namor',
    'vale te pego con todo',
    'bueno voy con namor',
    'ahora ataco con todos',
  ],
  DECLARE_BLOCKERS: [
    'bloqueo con namor',
    'bloqueo a wolverine con namor',
    'bloqueo ese con namor',
    'defiendo con yoshimaru',
    'defiendo namor con yoshimaru',
    'defiendo a namor con yoshimaru',
    'yoshimaru defiende namor',
    'voy a bloquear con namor',
    'pues bloqueo con namor',
    'vale bloqueo a ese con namor',
  ],
  NO_BLOCKS: [
    'no bloqueo',
    'sin bloqueo',
    'sin bloqueos',
    'sin bloquear',
    'no hay bloqueos',
    'nadie bloquea',
    'no hago bloqueos',
    'no bloqueo con nada',
    'pues no bloqueo',
    'vale sin bloqueos',
  ],
  DECLARE_DAMAGE: [
    'namor recibe tres',
    'namor se come tres',
    'le hago tres a namor',
    'sol ring recibe dos',
    'pues namor recibe cinco de dano',
    'vale le hago cuatro a wolverine',
  ],
  NEXT_TURN: [
    'paso turno',
    'te toca',
    'tu turno',
    'turno para ti',
    'pues paso turno',
    'vale te toca',
    'bueno termino turno',
  ],
  MULTI_ACTION: [
    'bajo isla y paso turno',
    'bajo isla y giro sol ring',
    'giro sol ring y lanzo remora',
    'robo y paso turno',
    'bajo isla luego lanzo remora y paso turno',
    'giro dos islas y lanzo counterspell',
    'ataco con namor y despues paso turno',
    'pues bajo isla y luego robo una',
    'vale giro sol ring lanzo remora y paso turno',
    'bueno bajo una isla despues giro sol ring',
  ],
  UNDO: [
    'cancela',
    'cancela eso',
    'deshaz',
    'deshaz eso',
    'anula eso',
    'revierte eso',
    'undo',
    'atras',
    'me he equivocado cancela',
  ],
  NOT_ACTION: [
    'creo que voy a bajar una isla',
    'igual bajo una isla',
    'quizas bajo isla',
    'a lo mejor juego una isla',
    'deberia bajar una isla',
    'puede que baje una isla',
    'si bajo una isla que pasa',
    'si bajo isla puedo jugar esto',
    'vas a bajar una isla',
    'puedo bajar una isla',
    'ayer baje una isla',
    'antes jugue una isla',
    'creo que voy a lanzar counterspell',
    'igual lanzo counterspell',
    'quizas te lanzo counterspell',
    'deberia lanzar counterspell',
    'puedo lanzar counterspell',
    'vas a lanzar counterspell',
    'si lanzas counterspell hago esto',
    'antes lance counterspell',
    'has lanzado counterspell',
    'tienes counterspell',
    'que hace counterspell',
    'como funciona counterspell',
    'creo que voy a atacar con namor',
    'igual ataco con namor',
    'quizas ataque con namor',
    'deberia atacar con namor',
    'vas a atacar con namor',
    'si atacas con namor bloqueo',
    'antes atacaste con namor',
    'has atacado con namor',
    'creo que robo ahora',
    'igual robo una',
    'deberia robar una carta',
    'has robado ya',
    'vas a robar',
    'cuantas cartas robas',
    'si robas una carta pasa esto',
    'creo que giro sol ring',
    'igual giro sol ring',
    'deberia girar sol ring',
    'puedo girar sol ring',
    'has girado sol ring',
    'por que has girado sol ring',
    'cuantas vidas tienes',
    'estoy pensando que hacer',
    'no se si atacar',
    'a ver que hago ahora',
    'que tienes en mesa',
    'que tienes en mano',
    'cuantas cartas tienes',
    'yo aqui jugaria remora',
    'yo aqui lanzaria counterspell',
    'en tu lugar atacaria con namor',
    'esto podria hacer cinco de dano',
  ],
}
