import { normalizeCommandText } from '../commands/parser/normalizeText'

/**
 * Curated tabletop vocabulary for Spanish speech recognition.
 *
 * This is recognition context, not an executable command list. Including a term
 * here must never make Jarvis perform an action by itself; the command parser,
 * contextual UI resolver and GameState legality checks remain authoritative.
 *
 * The list intentionally mixes official Spanish terminology with the English
 * words and loanwords commonly spoken at Magic tables (stack, trigger, ramp,
 * tutor, board wipe, etc.). Keep boosts modest in contextualVocabulary.ts so
 * this dictionary helps recognition without overpowering ordinary speech.
 */
export const MAGIC_VOICE_VOCABULARY = {
  zones: [
    'campo de batalla',
    'battlefield',
    'mesa',
    'mano',
    'hand',
    'biblioteca',
    'library',
    'mazo',
    'deck',
    'cementerio',
    'graveyard',
    'exilio',
    'exile',
    'pila',
    'stack',
    'zona de mando',
    'command zone',
  ],
  turnStructure: [
    'turno',
    'fase',
    'paso',
    'prioridad',
    'priority',
    'respuesta',
    'en respuesta',
    'mantengo prioridad',
    'hold priority',
    'enderezar',
    'untap',
    'mantenimiento',
    'upkeep',
    'paso de robar',
    'draw step',
    'primera principal',
    'main uno',
    'main one',
    'combate',
    'combat',
    'inicio de combate',
    'begin combat',
    'declarar atacantes',
    'declare attackers',
    'declarar bloqueadores',
    'declare blockers',
    'dano de combate',
    'combat damage',
    'segunda principal',
    'main dos',
    'main two',
    'paso final',
    'end step',
    'limpieza',
    'cleanup',
    'fin de turno',
    'end of turn',
  ],
  coreActions: [
    'jugar',
    'play',
    'lanzar',
    'cast',
    'castear',
    'resolver',
    'resuelve',
    'resolve',
    'activar',
    'activate',
    'habilidad activada',
    'habilidad disparada',
    'trigger',
    'triggered ability',
    'disparo',
    'girar',
    'tap',
    'tapear',
    'enderezar',
    'untap',
    'robar',
    'draw',
    'descartar',
    'discard',
    'barajar',
    'shuffle',
    'buscar',
    'search',
    'objetivo',
    'target',
    'hacer objetivo',
    'contrarrestar',
    'counter',
    'counterspell',
    'destruir',
    'destroy',
    'sacrificar',
    'sacrifice',
    'sacrificio',
    'exiliar',
    'exile',
    'devolver a la mano',
    'return to hand',
    'anexar',
    'attach',
    'equipar',
    'equip',
    'transformar',
    'transform',
    'fasear',
    'phase out',
    'phase in',
    'copiar',
    'copy',
    'crear ficha',
    'create token',
    'contador',
    'counter on',
    'valor de x',
    'mana',
    'mana pool',
    'reserva de mana',
    'fuente',
    'source',
    'control',
    'controlador',
    'controller',
    'coste',
    'cost',
    'coste adicional',
    'additional cost',
    'valor de mana',
    'mana value',
    'mareo de invocacion',
    'summoning sickness',
    'entra al campo de batalla',
    'enters the battlefield',
    'sale del campo de batalla',
    'leaves the battlefield',
  ],
  cardTypes: [
    'tierra',
    'land',
    'criatura',
    'creature',
    'artefacto',
    'artifact',
    'encantamiento',
    'enchantment',
    'instantaneo',
    'instant',
    'conjuro',
    'sorcery',
    'planeswalker',
    'batalla',
    'battle',
    'aura',
    'encantar',
    'enchant',
    'equipo',
    'equipment',
    'permanente',
    'permanent',
    'hechizo',
    'spell',
    'legendario',
    'legendary',
    'comandante',
    'commander',
  ],
  commonKeywords: [
    'volar',
    'flying',
    'alcance',
    'reach',
    'arrollar',
    'trample',
    'prisa',
    'haste',
    'vigilancia',
    'vigilance',
    'amenaza',
    'menace',
    'toque mortal',
    'deathtouch',
    'vinculo vital',
    'lifelink',
    'dano primero',
    'first strike',
    'dano doble',
    'double strike',
    'antimaleficio',
    'hexproof',
    'indestructible',
    'proteccion',
    'protection',
    'destello',
    'flash',
    'defensor',
    'defender',
    'ward',
    'rebatir',
    'adivinar',
    'scry',
    'escrutar',
    'surveil',
    'moler',
    'mill',
    'proliferar',
    'proliferate',
    'investigar',
    'investigate',
    'incitar',
    'goad',
    'retrospectiva',
    'flashback',
  ],
  commander: [
    'commander',
    'comandante',
    'zona de mando',
    'command zone',
    'impuesto de comandante',
    'commander tax',
    'dano de comandante',
    'commander damage',
    'identidad de color',
    'color identity',
    'mulligan',
  ],
  tabletopSlang: [
    'board',
    'board state',
    'board wipe',
    'wipe de mesa',
    'wipe',
    'wrath',
    'removal',
    'spot removal',
    'bounce',
    'bouncear',
    'blink',
    'blinkear',
    'flicker',
    'flickear',
    'tutor',
    'tutorear',
    'ramp',
    'rampear',
    'mana dork',
    'dork',
    'cantrip',
    'wheel',
    'topdeck',
    'top deck',
    'topdeckear',
    'lethal',
    'letal',
    'fetch',
    'fetchland',
    'shockland',
    'dual',
    'sac outlet',
    'etb',
    'ltb',
    'entra al campo',
    'sale del campo',
    'value',
    'tempo',
    'aggro',
    'control',
    'combo',
    'midrange',
    'board sweeper',
    'sweeper',
    'burn',
    'direct damage',
    'combat trick',
    'chump block',
    'swing',
    'alpha strike',
    'fizzle',
    'mana rock',
    'rock',
    'mana flood',
    'mana screw',
    'engine',
    'voltron',
    'aristocrats',
    'loot',
    'rummage',
    'reanimate',
    'ritual',
    'anthem',
    'lord',
    'sac',
    'yard',
    'bin',
    'grave hate',
    'hate piece',
    'silver bullet',
    'wincon',
    'win condition',
  ],
  commonResources: [
    'ficha',
    'token',
    'tesoro',
    'treasure',
    'comida',
    'food',
    'pista',
    'clue',
    'sangre',
    'blood',
    'contador mas uno mas uno',
    'contador menos uno menos uno',
    'contador de lealtad',
    'loyalty counter',
    'contador de experiencia',
    'experience counter',
  ],
} as const

export const MAGIC_VOICE_COMMON_TERMS: string[] = [
  ...new Set(
    Object.values(MAGIC_VOICE_VOCABULARY)
      .flat()
      .map((term) => normalizeCommandText(term))
      .filter(Boolean),
  ),
]
